spring:
  application:
    name: msvc-paciente
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true